version: "3.8"

services:
  desafio-postgres:
    image: postgres:latest
    restart: always
    volumes:
      - ./desafio-init.sql:/docker-entrypoint-initdb.d/init.sql
      - desafio-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: desafio
    ports:
      - "5444:5432"
    networks:
      - postgres-compose-network

  desafio-app:
    build:
      context: ../                # volta para /desafio (onde está o Dockerfile)
      dockerfile: Dockerfile      # garante que o Dockerfile correto seja usado
    ports:
      - "8080:8080"
    depends_on:
      - desafio-postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://desafio-postgres:5432/desafio
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 123
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge

volumes:
  desafio-data:
